---
title: "Lucas Veras's CV"
author: Lucas Veras
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1lmTkQPjWL7ZVcTD2nIzMpnMSFe14XAe-Njb3PN3smcQ/edit#gid=917338460",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with
# some conditional CSS.
if (params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
===========================================================================

Contact {#contact}
---------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

Programming skills {#skills}
---------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```


Disclaimer {#disclaimer}
---------------------------------------------------------------------------

```{r}
if(params$pdf_mode){
  cat("View this CV online at _nickstrayer.me/datadrivencv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/nstrayer/cv/raw/master/strayer_cv.pdf)")
}
```

The source code is available on [GitHub](https://github.com/verasls/verasls.github.io/tree/master/CV).

Last updated on `r Sys.Date()`.


Main
===========================================================================

Lucas Veras {#title}
---------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
# Uncomment the line below if you want to add an intro text at the
# beginning of the CV
# CV %<>% print_text_block("intro") 
```

Education {data-icon=graduation-cap data-concise=true}
---------------------------------------------------------------------------

```{r}
CV %<>% print_section("education")
```

Papers {data-icon=file-alt data-concise=true}
---------------------------------------------------------------------------

```{r}
CV %<>% print_section("papers")
```

Conference proceedings {data-icon=chalkboard data-concise=true}
---------------------------------------------------------------------------

```{r}
CV %<>% print_section("conference")
```

Awards {data-icon=award data-concise=true}
---------------------------------------------------------------------------

```{r}
CV %<>% print_section("awards")
```
